
spring:
  application:
    name: eureka-server
  security: 
    user:
     name: ''
     password: ''
      
server:
  port: 8761
 
   
       
eureka:

  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
     
      defaultZone: http://'':8761/eureka/
    
